### ISSUE TITLE
Customize Fabmanager looks for production website

### ISSUE THREAD

**Issue by lpgn** [bkp123/BKP-fab-manager-BKP#20]
@emj365 Customize Fabmanager looks for production website

**Comment by emj365** [comment]
Maybe we can try "heroku" first. It's easier than VPS.

**Comment by lpgn** [comment]
Why heroku is easier?

**Comment by emj365** [comment]
Because you don't need setup service app like Nginx or install dependencies in server. Just config your deploy app "cap" push your code to Heroku.
